export default {
  FETCH_SCHEDULE: "FETCH_SCHEDULE",
  FETCH_SCHEDULE_SUCCESS: "FETCH_SCHEDULE_SUCCESS",
  FETCH_SCHEDULE_FAILED: "FETCH_SCHEDULE_FAILED",
  UPDATE_EVENT_DATE: "UPDATE_EVENT_DATE",
  UPDATE_EVENT_DATE_SUCCESS: "UPDATE_EVENT_DATE_SUCCESS",
  UPDATE_EVENT_DATE_FAILED: "UPDATE_EVENT_DATE_FAILED",
};
